### PR TITLE
Lightning talk or talk 

### PR DESCRIPTION
**Pull request by rtpavlovsk21**
@katyhuff @staeiou blah! i was thinking about doing this and I guess i made it halfway through... i want to finish a metaclass example this week. maybe just a lightning talk...

### CODE REVIEW

**Comment by Carreau** [comment]
oh ! A Python 2 Notebook ! Where are my parentheses around print :-P

**Comment by Carreau** [comment]
Tips us [functools.wraps](https://docs.python.org/3.5/library/functools.html#functools.wraps)  for better inspection of decorated functions signatures. 


And you can use https://gist.github.com/takluyver/c8839593c615bb2f6e80 to run 2to3 on a notebook :-D

**Comment by katyhuff** [comment]
bitmoji
Excellent, @rtpavlovsk21 ! It looks good. Since you asked for critique, I will say that, given that decorators are a pretty abstract notion, it is probably helpful to motivate them with a compelling example. If there's a more "real world" example that could be worked into this where there are currently sums, then perhaps that would be easier for folks to grok. It's not necessary though, if you explain the need for decorators clearly enough.

Also, I have an idea! !

bitmoji

- Next week, on March 2, we need a topic.  
- @rtpavlovsk21 , you could start March 2 by giving this talk, which I think will only take about 20 minutes and I think will be interesting to folks!
- and @Carreau , you could follow it up by give a 10-20 minute talk on various ways to convert python scripts and notebooks and packages and everything else to python 3. You know... give everyone the rundown about import future, import six, the 2to3 script, etc.... You could have room to opine all you want!

What do you two (and @staeiou ) think about that?

**Comment by Carreau** [comment]
> You could have room to opine all you want!

Ok, i'll try to do that, and show some nbconvert stuff.

**Comment by rtpavlovsk21** [comment]
Sounds good to me, see you.

On Tue, Feb 23, 2016 at 5:50 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> You could have room to opine all you want!
>
> Ok, i'll try to do that, and show some nbconvert stuff.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thehackerwithin/berkeley/pull/53#issuecomment-188006041>
> .
>



-- 
Ryan Pavlovsky
Nuclear Engineering Graduate Student
rp@berkeley.edu <rtpavlovsky@nuc.berkeley.edu>

**Comment by katyhuff** [comment]
Great! I'm going to put you both on the schedule for March 2, then. Ryan,
feel free free to merge your own private when it's ready. Both of you are
welcome to push anything you like up to the repository as needed.

**Comment by tkelman** [comment]
@katyhuff I think you may have forgotten to merge this?

**Comment by katyhuff** [comment]
Thanks!

On Wed, Mar 9, 2016 at 9:40 AM, Ryan Pavlovsky <notifications@github.com>
wrote:

> Merged #53 <https://github.com/thehackerwithin/berkeley/pull/53>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thehackerwithin/berkeley/pull/53#event-583653135>.
>



-- 
http://katyhuff.github.com

**Pull request merged**
