### PR TITLE
Add brief description and links to UNIX/BASH post

### PR DESCRIPTION
**Pull request by akokai**
We can revise with any feedback through this PR...

### CODE REVIEW

**Comment by Carreau** [comment]
+1 on the GIF. 

https://github.com/veltman/clmystery link maybe for people to train if needed. 

We need to think about quick instructions on how to setup bash on windows. (probably git-bash or linux subsytem). 

For people afraid of damaging their computer, and who don't want to run docker, have a github account and can use ssh, https://dply.co provide 2h free servers. Quite useful but need to start from scratch.

**Comment by akokai** [comment]
Thanks @Carreau, I took those suggestions. (I have never used Docker so I won't be of help for people actually doing that.)

**Comment by Carreau** [comment]
@staeiou may I get commit rights ?

**Comment by staeiou** [comment]
@Carreau invite sent!

**Comment by Carreau** [comment]
Thanks !

**Pull request merged**
